# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SaveStateWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveState(object):
    def setupUi(self, SaveState):
        SaveState.setObjectName("SaveState")
        SaveState.resize(626, 453)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SaveState.sizePolicy().hasHeightForWidth())
        SaveState.setSizePolicy(sizePolicy)
        SaveState.setMinimumSize(QtCore.QSize(70, 60))
        SaveState.setSizeIncrement(QtCore.QSize(800, 100))
        self.layout = QtWidgets.QGridLayout(SaveState)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setSpacing(0)
        self.layout.setObjectName("layout")
        self.label = QtWidgets.QLabel(SaveState)
        self.label.setMinimumSize(QtCore.QSize(10, 10))
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.layout.addWidget(self.label, 0, 0, 2, 1)
        self.network_surface = NetworkSurfaceWidget(SaveState)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.network_surface.sizePolicy().hasHeightForWidth())
        self.network_surface.setSizePolicy(sizePolicy)
        self.network_surface.setMinimumSize(QtCore.QSize(30, 30))
        self.network_surface.setMaximumSize(QtCore.QSize(300, 300))
        self.network_surface.setSizeIncrement(QtCore.QSize(0, 0))
        self.network_surface.setObjectName("network_surface")
        self.layout.addWidget(self.network_surface, 0, 1, 2, 1)
        self.clear_button = QtWidgets.QPushButton(SaveState)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        self.clear_button.setMinimumSize(QtCore.QSize(24, 24))
        self.clear_button.setMaximumSize(QtCore.QSize(35, 35))
        self.clear_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./util/ressources/eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_button.setIcon(icon)
        self.clear_button.setIconSize(QtCore.QSize(24, 24))
        self.clear_button.setObjectName("clear_button")
        self.layout.addWidget(self.clear_button, 0, 2, 1, 1)
        self.view_button = QtWidgets.QPushButton(SaveState)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_button.sizePolicy().hasHeightForWidth())
        self.view_button.setSizePolicy(sizePolicy)
        self.view_button.setMinimumSize(QtCore.QSize(24, 24))
        self.view_button.setMaximumSize(QtCore.QSize(35, 35))
        self.view_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./util/ressources/clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_button.setIcon(icon1)
        self.view_button.setIconSize(QtCore.QSize(24, 24))
        self.view_button.setObjectName("view_button")
        self.layout.addWidget(self.view_button, 1, 2, 1, 1)

        self.retranslateUi(SaveState)
        self.clear_button.clicked.connect(SaveState.view)
        self.view_button.clicked.connect(SaveState.clear)
        QtCore.QMetaObject.connectSlotsByName(SaveState)

    def retranslateUi(self, SaveState):
        _translate = QtCore.QCoreApplication.translate
        SaveState.setWindowTitle(_translate("SaveState", "Frame"))
        self.label.setText(_translate("SaveState", "-1"))

from util.hopfield_QTHelper import NetworkSurfaceWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveState = QtWidgets.QFrame()
    ui = Ui_SaveState()
    ui.setupUi(SaveState)
    SaveState.show()
    sys.exit(app.exec_())
